### ISSUE TITLE
Component trace never starts

### ISSUE THREAD

**Issue by Knear2** [rlewicki/MeleeTrace#7]
My weapon it's his own blueprint character and keeps all the attack logic and the melee component, my character only calls it, however, when i attack, the line trace never starts, only seems to work if my weapon is attatched to the player.
Here i attach a picutre of the logic inside of the weapon.
![screenshot](https://github.com/rlewicki/MeleeTrace/assets/150719719/a075708c-fac4-433f-9b47-3dd067b1b97e)

**Comment by rlewicki** [comment]
Hey @Knear2 thanks for reaching out. I'll have a look at the problem later tonight and will try to help you.

**Comment by rlewicki** [comment]
Okay, so case you are describing should work without any problems honestly. The trace component searches for ANY static or skeletal mesh components attached  to the owner. So if the weapon is an actor itself and it has a static/skeletal mesh component and trace component it should find it.

Perhaps your weapon mesh doesn't have sockets with the names you define them? This is very important, otherwise the system will never start tracing. Here is a code snippet:
```cpp
	TArray<UActorComponent*> MeshComponents;
	GetOwner()->GetComponents(UMeshComponent::StaticClass(), MeshComponents);
	for (UActorComponent* MeshComponent : MeshComponents)
	{
		UMeshComponent* TypedMeshComponent = Cast<UMeshComponent>(MeshComponent);
		check(TypedMeshComponent);
		if (TypedMeshComponent->DoesSocketExist(MeleeTraceInfo.StartSocketName)
			&& TypedMeshComponent->DoesSocketExist(MeleeTraceInfo.EndSocketName))
		.
		.
		.
```
As you can see, both `StartSocketName` and `EndSocketName` must exist in selected mesh component for system to proceed to start tracing.

Let me know if you need any further help!

**Comment by DawnDevelop** [comment]
Hi, @rlewicki I guess what they mean is that they have a Blueprint which contains a skeletal mesh of the weapon with the sockets, and it is attached at runtime. For example, this is the Blueprint of my weapon:

![image](https://github.com/rlewicki/MeleeTrace/assets/32778430/e1217454-467c-4e37-a059-e94588cdb57a)

Just for demo purposes, I attach it at runtime to my main player character:
![image](https://github.com/rlewicki/MeleeTrace/assets/32778430/6ed1d24f-4ee2-45ab-8437-dc266ae6df9f)


The current code creates an array with all components of the owner actor that are of type UMeshComponent or derived from UMeshComponent. The problem is that the Skeletal Mesh we want to get the socket from is inside the **BP_Katana**.

To get the Skeletal Mesh inside the Blueprint, we would need something like the following, where we also check the meshes inside attached actors. **Here is my take on the updated code:**

```cpp
void UMeleeTraceComponent::StartTrace(const FMeleeTraceInfo& MeleeTraceInfo, uint32 TraceHash)
{
	AActor* Owner = GetOwner();

	TArray<UActorComponent*> MeshComponents;
	TArray<AActor*> ActorsToCheck = { Owner };
	TArray<AActor*> AttachedActors;

	Owner->GetAttachedActors(AttachedActors);
	ActorsToCheck.Append(AttachedActors);

	for (AActor* Actor : ActorsToCheck)
	{
		TArray<UActorComponent*> ActorMeshComponents;
		Actor->GetComponents(UMeshComponent::StaticClass(), ActorMeshComponents);
		MeshComponents.Append(ActorMeshComponents);
	}

	for (UActorComponent* MeshComponent : MeshComponents)
	{
		UMeshComponent* TypedMeshComponent = Cast<UMeshComponent>(MeshComponent);
		check(TypedMeshComponent);

		if (TypedMeshComponent->DoesSocketExist(MeleeTraceInfo.StartSocketName) 
			&& TypedMeshComponent->DoesSocketExist(MeleeTraceInfo.EndSocketName))
		{
			FActiveMeleeTraceInfo& NewMeleeTraceInfo = ActiveMeleeTraces.AddDefaulted_GetRef();
			NewMeleeTraceInfo.MeleeTraceInfo = MeleeTraceInfo;
			NewMeleeTraceInfo.TraceHash = TraceHash;
			NewMeleeTraceInfo.SourceMeshComponent = TypedMeshComponent;
			GetTraceSamples(TypedMeshComponent, MeleeTraceInfo, NewMeleeTraceInfo.PreviousFrameSampleLocations);
			OnTraceStart.Broadcast(this);
			return;
		}
	}

	ensureAlwaysMsgf(false,
		TEXT("None of the USkeletalMeshComponents contain sockets with names: %s and %s"),
		*MeleeTraceInfo.StartSocketName.ToString(),
		*MeleeTraceInfo.EndSocketName.ToString());
}
```

It's not properly tested, but it works for me.

Thank you for your time and nice work on the Plugin!

**Comment by DawnDevelop** [comment]
I opened a PR if you want to take a look at the changes

**Comment by rlewicki** [comment]
@DawnDevelop ah I see it now. It's true I have not considered a case where a weapon is it's own child actor rather then simply a mesh attached to the owner.

Thanks for opening the pull request, I'll try to have a look at it today or tomorrow!
